// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI (migrations) : connexion directe Supabase si définie, sinon DATABASE_URL
    url:
      process.env["DIRECT_DATABASE_URL"] ??
      process.env["DATABASE_URL"] ??
      "",
  },
});
