export const CLOUDINARY_CONSTANTS = {
  MAX_FILE_SIZE_BYTES: 5 * 1024 * 1024,
  ALLOWED_MIME_TYPES: [
    'image/jpeg',
    'image/jpg',
    'image/pjpeg',
    'image/png',
    'image/webp',
    'image/svg+xml',
    'application/octet-stream',
  ] as const,
  ALLOWED_EXTENSIONS: ['.jpg', '.jpeg', '.png', '.webp', '.svg'] as const,
  PROFILE_FOLDER: 'bibliotech/profiles',
  BADGE_FOLDER: 'bibliotech/badges',
  COVER_FOLDER: 'bibliotech/covers',
  BADGE_TRANSFORM: {
    width: 256,
    height: 256,
    crop: 'limit' as const,
    quality: 'auto' as const,
    fetch_format: 'auto' as const,
  },
  COVER_TRANSFORM: {
    width: 800,
    height: 1200,
    crop: 'limit' as const,
    quality: 'auto' as const,
    fetch_format: 'auto' as const,
  },
  PROFILE_PUBLIC_ID: 'avatar',
  PROFILE_TRANSFORM: {
    width: 500,
    height: 500,
    crop: 'fill' as const,
    gravity: 'face' as const,
    quality: 'auto' as const,
    fetch_format: 'auto' as const,
  },
  /** Durée des signed URLs livre (RG39 / RG40) */
  BOOK_SIGNED_URL_SECONDS: 2 * 60 * 60,
  BOOK_FOLDER: 'bibliotech/livres',
  MAX_BOOK_FILE_SIZE_BYTES: 50 * 1024 * 1024,
  ALLOWED_BOOK_MIME_TYPES: [
    'application/pdf',
    'application/epub+zip',
    'application/vnd.epub+zip',
    'application/x-mobipocket-ebook',
    'application/octet-stream',
  ] as const,
  ALLOWED_BOOK_EXTENSIONS: ['.pdf', '.epub', '.mobi'] as const,
} as const;
