export const RECOMMENDATIONS_CONSTANTS = {
  MAX_TOTAL_PER_REFRESH: 50,
  MAX_PICKS_DEFAULT: 10,
  MAX_SIMILAR_DEFAULT: 12,
  TRENDING_WINDOW_DAYS: 14,
  SEARCH_HISTORY_LOOKBACK: 10,
  SEARCH_SCORE_BOOST: 0.05,
  FINISHED_BOOKS_LOOKBACK: 20,
  SCORE_MIN: 0.55,
  SCORE_MAX: 0.99,
} as const;
