export const AUTH_CONSTANTS = {
  OTP_LENGTH: 6,
  OTP_EXPIRY_MINUTES: 10,
  OTP_GEN_WINDOW_MINUTES: 15,
  OTP_GEN_MAX: 3,
  OTP_VERIFY_WINDOW_MINUTES: 15,
  OTP_VERIFY_MAX: 5,
  JWT_EXPIRES: '15m',
  JWT_EXPIRES_SECONDS: 15 * 60,
  REFRESH_EXPIRES_DAYS: 30,
  BCRYPT_ROUNDS: 12,
  REDIS_JTI_PREFIX: 'jwt:blacklist:',
} as const;
